// src/components/booking/MobileStickyBar.tsx
"use client";

import Link from "next/link";
import { MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";

export function MobileStickyBar({
  propertyId,
}: {
  propertyId: string;
}) {
  function openChat() {
    window.dispatchEvent(new CustomEvent("open-concierge-chat"));
  }

  return (
    <div className="fixed inset-x-4 bottom-3 z-40 md:hidden">
      <div className="mx-auto flex max-w-sm translate-y-1 items-center gap-2 rounded-full border border-border/80 bg-background/90 p-2 shadow-2xl shadow-black/25 backdrop-blur-xl transition-transform duration-300 focus-within:translate-y-0 hover:translate-y-0 dark:bg-card/90">
        <Link
          href={`/booking?unit=${propertyId}`}
          className="flex h-12 flex-1 items-center justify-center rounded-full bg-gold px-5 text-sm font-semibold text-navy shadow-lg shadow-gold/20 transition hover:bg-gold-light"
        >
          Book
        </Link>
        <Button
          type="button"
          onClick={openChat}
          variant="outline"
          size="icon"
          className="h-12 w-12 shrink-0 rounded-full bg-card"
          aria-label="Open concierge chat"
        >
          <MessageCircle className="h-5 w-5" />
        </Button>
      </div>
    </div>
  );
}

// archive/sveltekit-prototype/src/lib/components/booking/MobileStickyBar.svelte
<script lang="ts">
	import { goto } from '$app/navigation';

	let {
		pricePerNight,
		propertyId
	}: {
		pricePerNight: number;
		propertyId: string;
	} = $props();

	function handleBook() {
		goto('/booking?unit=' + propertyId);
	}
</script>

<div class="fixed bottom-0 left-0 right-0 z-50 border-t border-border bg-card px-4 py-3 shadow-[0_-4px_20px_rgba(0,0,0,0.1)] md:hidden" style="padding-bottom: max(0.75rem, env(safe-area-inset-bottom))">
	<div class="flex items-center justify-between">
		<div>
			<div class="flex items-baseline gap-1.5">
				<span class="text-lg font-bold text-card-foreground">&#3647;{pricePerNight.toLocaleString()}</span>
			</div>
			<p class="text-[11px] text-muted-foreground">/night &middot; Direct price</p>
		</div>
		<button
			onclick={handleBook}
			class="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground shadow-lg transition hover:bg-primary/90"
		>
			Book
		</button>
	</div>
</div>
