// src/lib/components/story/TourConclusion.svelte
<script lang="ts">
	import { narrativeState } from '$lib/stores/narrative.svelte';
	import { getConclusionForProperty } from '$lib/data/tourflow';
	import type { Property } from '$lib/data/properties';

	let { property, onclose }: { property: Property; onclose: () => void } = $props();
	let conclusion = $derived(getConclusionForProperty(property.id));
	let checkIn = $state('');
	let checkOut = $state('');
	let guests = $state(2);

	function incrementGuests() { if (guests < property.maxGuests) guests++; }
	function decrementGuests() { if (guests > 1) guests--; }
	const today = new Date().toISOString().split('T')[0];
</script>

{#if conclusion}
	<div class="conclusion-enter absolute inset-0 z-30 flex items-center justify-center overflow-y-auto bg-black/60 backdrop-blur-sm">
		<div class="mx-auto w-full max-w-lg px-5 py-10 md:px-6 md:py-16">
			<button onclick={onclose} class="absolute right-4 top-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white/70 transition hover:bg-white/20 hover:text-white md:right-6 md:top-6" aria-label="Back to tour">
				<svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
			</button>

			<div class="relative overflow-hidden rounded-2xl">
				<img src={property.images[0]} alt={property.name} class="aspect-[16/10] w-full object-cover" />
				<div class="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent"></div>
				<div class="absolute inset-x-0 bottom-0 px-6 pb-6">
					<p class="text-xs font-medium uppercase tracking-widest text-white/60">{property.name}</p>
					<h2 class="mt-1 font-serif text-3xl font-semibold text-white md:text-4xl" style="text-shadow: 0 2px 12px rgba(0,0,0,0.5);">{conclusion.headline}</h2>
				</div>
			</div>

			<p class="mt-6 text-sm leading-relaxed text-white/80 md:text-base">{conclusion.summary}</p>

			<ul class="mt-5 space-y-2.5">
				{#each conclusion.highlights as highlight}
					<li class="flex items-start gap-3 text-sm text-white/90 md:text-base">
						<svg class="mt-0.5 h-4 w-4 flex-shrink-0 text-sky-400" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd" /></svg>
						{highlight}
					</li>
				{/each}
			</ul>

			<div class="mt-6 flex items-baseline gap-1.5">
				<span class="text-2xl font-bold text-white md:text-3xl">&#3647;{property.pricePerNight.toLocaleString()}</span>
				<span class="text-sm text-white/50">/night</span>
			</div>

			<div class="mt-5 space-y-3">
				<div class="grid grid-cols-2 gap-3">
					<div>
						<label for="checkin" class="mb-1 block text-xs font-medium uppercase tracking-wider text-white/50">Check-in</label>
						<input id="checkin" type="date" bind:value={checkIn} min={today} class="w-full rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-sm text-white backdrop-blur-sm transition focus:border-sky-400/50 focus:outline-none focus:ring-1 focus:ring-sky-400/30" />
					</div>
					<div>
						<label for="checkout" class="mb-1 block text-xs font-medium uppercase tracking-wider text-white/50">Check-out</label>
						<input id="checkout" type="date" bind:value={checkOut} min={checkIn || today} class="w-full rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-sm text-white backdrop-blur-sm transition focus:border-sky-400/50 focus:outline-none focus:ring-1 focus:ring-sky-400/30" />
					</div>
				</div>
				<div>
					<label for="guests-display" class="mb-1 block text-xs font-medium uppercase tracking-wider text-white/50">Guests</label>
					<div class="flex items-center gap-3">
						<button onclick={decrementGuests} disabled={guests <= 1} aria-label="Fewer guests" class="flex h-10 w-10 items-center justify-center rounded-xl border border-white/20 bg-white/10 text-white transition hover:bg-white/20 disabled:opacity-30">
							<svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4" /></svg>
						</button>
						<span id="guests-display" class="min-w-[3rem] text-center text-sm font-medium text-white">{guests} guest{guests > 1 ? 's' : ''}</span>
						<button onclick={incrementGuests} disabled={guests >= property.maxGuests} aria-label="More guests" class="flex h-10 w-10 items-center justify-center rounded-xl border border-white/20 bg-white/10 text-white transition hover:bg-white/20 disabled:opacity-30">
							<svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" /></svg>
						</button>
					</div>
				</div>
			</div>

			<button class="mt-6 w-full rounded-2xl bg-sky-500 py-3.5 text-sm font-semibold text-white shadow-lg shadow-sky-500/25 transition-all duration-300 hover:bg-sky-400 hover:shadow-sky-500/40 md:text-base">Book Your Stay</button>

			<div class="mt-3 text-center">
				<button class="text-sm text-white/50 transition hover:text-white/80" onclick={() => narrativeState.showLeadCapture()}>Save This Dream</button>
			</div>

			<p class="mt-6 text-center font-serif text-sm italic text-white/40" style="text-shadow: 0 1px 4px rgba(0,0,0,0.3);">{conclusion.closingLine}</p>
		</div>
	</div>
{/if}

<style>
	@keyframes conclusion-enter { from { opacity: 0; } to { opacity: 1; } }
	:global(.conclusion-enter) { animation: conclusion-enter 0.8s ease-out forwards; }
	input[type='date']::-webkit-calendar-picker-indicator { filter: invert(1) brightness(0.7); }
</style>

// src/components/tour/TourConclusion.tsx
"use client";

import { useRouter } from "next/navigation";
import { Check, Minus, Plus, X } from "lucide-react";
import { useState } from "react";
import { BookingDatePicker } from "@/components/booking/BookingDatePicker";
import { PropertyImage } from "@/components/property/PropertyImage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getConclusionForProperty } from "@/lib/data/tourflow";
import { dateToIso, todayIsoLocal } from "@/lib/booking/dates";
import type { Property } from "@/lib/data/properties";

export function TourConclusion({
  property,
  onClose,
  onLead,
}: {
  property: Property;
  onClose: () => void;
  onLead: () => void;
}) {
  const router = useRouter();
  const conclusion = getConclusionForProperty(property.id);
  const [checkIn, setCheckIn] = useState("");
  const [nights, setNights] = useState(1);
  const [adults, setAdults] = useState(Math.min(2, property.maxGuests));
  const [children, setChildren] = useState(0);
  const totalGuests = adults + children;
  if (!conclusion) return null;

  function book() {
    const params = new URLSearchParams({ unit: property.id });
    if (checkIn) params.set("checkin", checkIn);
    params.set("nights", String(nights));
    params.set("adults", String(adults));
    if (children > 0) params.set("children", String(children));
    params.set("guests", String(totalGuests));
    router.push(`/booking?${params.toString()}`);
  }

  function isArrivalDisabled(date: Date) {
    const iso = dateToIso(date);
    return iso < todayIsoLocal();
  }

  function updateNights(value: number) {
    setNights(Math.max(1, Math.min(60, Math.floor(value) || 1)));
  }

  function updateAdults(value: number) {
    const nextAdults = Math.max(1, Math.min(property.maxGuests, value));
    const maxChildren = Math.max(0, property.maxGuests - nextAdults);
    setAdults(nextAdults);
    if (children > maxChildren) setChildren(maxChildren);
  }

  function updateChildren(value: number) {
    setChildren(Math.max(0, Math.min(property.maxGuests - adults, value)));
  }

  return (
    <div className="absolute inset-0 z-30 flex items-center justify-center overflow-y-auto bg-black/60 px-5 py-10 backdrop-blur-sm">
      <Button
        type="button"
        variant="ghost"
        size="icon"
        onClick={onClose}
        className="fixed right-4 top-4 z-40 h-11 w-11 rounded-full bg-white/15 text-white shadow-lg shadow-black/30 backdrop-blur-md hover:bg-white/25 hover:text-white md:right-6 md:top-6"
        aria-label="Back to tour"
      >
        <X className="h-5 w-5" />
      </Button>
      <div className="mx-auto w-full max-w-lg">
        <div className="relative overflow-hidden rounded-2xl">
          <PropertyImage
            images={property.images}
            alt={property.name}
            className="aspect-[16/10]"
            sizes="(min-width: 768px) 560px, 100vw"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" />
          <div className="absolute inset-x-0 bottom-0 px-6 pb-6">
            <p className="text-xs font-medium uppercase tracking-widest text-white/60">
              {property.name}
            </p>
            <h2 className="mt-1 font-serif text-3xl font-semibold text-white md:text-4xl">
              {conclusion.headline}
            </h2>
          </div>
        </div>
        <p className="mt-6 text-sm leading-relaxed text-white/80 md:text-base">
          {conclusion.summary}
        </p>
        <ul className="mt-5 space-y-2.5">
          {conclusion.highlights.map((highlight) => (
            <li key={highlight} className="flex items-start gap-3 text-sm text-white/90 md:text-base">
              <Check className="mt-0.5 h-4 w-4 flex-shrink-0 text-gold" />
              {highlight}
            </li>
          ))}
        </ul>
        <div className="mt-5 space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div className="[&_button]:border-white/15 [&_button]:bg-white/10 [&_button]:text-white [&_label]:text-xs [&_label]:font-medium [&_label]:uppercase [&_label]:tracking-wider [&_label]:text-white/50">
              <BookingDatePicker
                label="Select date"
                value={checkIn}
                onChange={setCheckIn}
                isDateDisabled={isArrivalDisabled}
                placeholder="Arrival"
              />
            </div>
            <Label className="text-xs font-medium uppercase tracking-wider text-white/50">
              Nights
              <Input
                type="number"
                min={1}
                max={60}
                value={nights}
                onChange={(event) => updateNights(Number(event.target.value))}
                className="mt-1 border-white/15 bg-white/10 text-sm text-white [color-scheme:dark]"
              />
            </Label>
          </div>
          <div>
            <p className="mb-2 text-xs font-medium uppercase tracking-wider text-white/50">Guests</p>
            <div className="space-y-2">
              {[
                { label: "Adults", value: adults, min: 1, update: updateAdults },
                { label: "Children", value: children, min: 0, update: updateChildren },
              ].map((item) => (
                <div key={item.label} className="flex items-center justify-between rounded-xl border border-white/15 bg-white/10 px-3 py-2">
                  <span className="text-sm font-medium text-white">{item.label}</span>
                  <div className="flex items-center gap-2">
                    <Button
                      type="button"
                      variant="outline"
                      size="icon"
                      onClick={() => item.update(item.value - 1)}
                      disabled={item.value <= item.min}
                      className="h-9 w-9 rounded-xl border-white/20 bg-white/10 text-white hover:bg-white/15"
                    >
                      <Minus className="h-4 w-4" />
                    </Button>
                    <span className="w-7 text-center text-sm font-semibold text-white">{item.value}</span>
                    <Button
                      type="button"
                      variant="outline"
                      size="icon"
                      onClick={() => item.update(item.value + 1)}
                      disabled={totalGuests >= property.maxGuests}
                      className="h-9 w-9 rounded-xl border-white/20 bg-white/10 text-white hover:bg-white/15"
                    >
                      <Plus className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
        <Button variant="gold" className="mt-6 w-full rounded-2xl py-3.5" onClick={book}>
          Book
        </Button>
        <div className="mt-3 text-center">
          <button
            type="button"
            className="text-sm text-white/50 transition hover:text-white/80"
            onClick={onLead}
          >
            Save This Dream
          </button>
        </div>
        <p className="mt-6 text-center font-serif text-sm italic text-white/40">
          {conclusion.closingLine}
        </p>
      </div>
    </div>
  );
}
