// src/components/tour/RoomSphere.tsx
import type { Ref } from "react";
import { BackSide, type MeshBasicMaterial, type Texture } from "three";

export function RoomSphere({
  texture,
  opacity = 1,
  materialRef,
}: {
  texture: Texture;
  opacity?: number;
  materialRef?: Ref<MeshBasicMaterial>;
}) {
  return (
    <mesh rotation={[0, Math.PI, 0]}>
      <sphereGeometry args={[500, 60, 40]} />
      <meshBasicMaterial
        ref={materialRef}
        map={texture}
        side={BackSide}
        transparent={opacity < 1}
        opacity={opacity}
        depthWrite={false}
      />
    </mesh>
  );
}

// src/lib/components/RoomSphere.svelte
<script lang="ts">
	import { T } from '@threlte/core';
	import { BackSide, type Texture } from 'three';

	let { texture, opacity = 1 }: { texture: Texture; opacity?: number } = $props();
</script>

<T.Mesh>
	<T.SphereGeometry args={[500, 60, 40]} />
	<T.MeshBasicMaterial
		map={texture}
		side={BackSide}
		transparent={opacity < 1}
		{opacity}
		depthWrite={false}
	/>
</T.Mesh>
