// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Moon, Monitor, Sun } from "@lucide/svelte";
  import { themeState } from "$lib/stores/theme.svelte";

  let { solid = true }: { solid?: boolean } = $props();
</script>

<button
  onclick={() => themeState.cycle()}
  class="flex h-9 w-9 items-center justify-center rounded-full transition-colors {solid
    ? 'bg-muted text-foreground hover:bg-muted/80'
    : 'text-white/60 hover:bg-white/10 hover:text-white'}"
  aria-label="Toggle theme: {themeState.mode}"
>
  {#if themeState.mode === "light"}
    <Sun class="h-4 w-4" />
  {:else if themeState.mode === "dark"}
    <Moon class="h-4 w-4" />
  {:else}
    <Monitor class="h-4 w-4" />
  {/if}
</button>

// src/components/global/ThemeToggle.tsx
"use client";

import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function ThemeToggle({ solid = true }: { solid?: boolean }) {
  const [dark, setDark] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("theme");
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const nextDark = saved ? saved === "dark" : prefersDark;
    setDark(nextDark);
    document.documentElement.classList.toggle("dark", nextDark);
  }, []);

  function toggle() {
    const next = !dark;
    setDark(next);
    document.documentElement.classList.toggle("dark", next);
    localStorage.setItem("theme", next ? "dark" : "light");
  }

  return (
    <Button
      type="button"
      variant="ghost"
      size="icon"
      onClick={toggle}
      aria-label="Toggle theme"
      className={cn(
        "h-9 w-9 rounded-full",
        solid
          ? "text-foreground hover:bg-muted"
          : "text-white hover:bg-white/10",
      )}
    >
      {dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
    </Button>
  );
}
